### ISSUE TITLE
Internet page

### ISSUE THREAD

**Issue by Jermo13** [kcaf/PokeRadar#30] opened 2018-02-01 19:43 UTC
As soon as I start up minecraft with the mod installed it opens a page on internet https://kcaf.github.io/PokeRadar/  . I don't want this, is there a way to turn this off or is it a bug or something?

**Comment by kcaf** [comment] 2018-02-01 19:52
It's working as intended. The mod is completely free to use, but does take up time. That page exists to help support the time it takes to develop PokeRadar. You can choose to keep the page open (which helps me earn a couple of pennies) or close it. I'd rather do this method as it feels less intrusive than spamming the users with ads. I'm sorry this is an inconvenience, but it's the only solution I can come up with. If you have any suggestions, I'm 100% open to listen :)

**Comment by Jermo13** [comment] 2018-02-01 20:01
Soo I only have to have it open to help you out? Nothing else?And qua sugestions i dont really knoe maybe you can make it so it doesnt show the ability and such as you rightclick the pokemon to ride it? I dont know im just saying something.

the top line seems a bit odd.
![2018-02-01_20 58 21](https://user-images.githubusercontent.com/34963120/35700264-cbbd0ade-0792-11e8-88de-2a846811d900.png)

**Comment by Jermo13** [comment] 2018-02-01 20:04
Oh and thanks for reacting so fast!

**Comment by kcaf** [comment] 2018-02-01 20:07
@Jermo13 That's all, just keep the tab open and you'll help buy me a coffee! I greatly appreciate it!!

I've also written a little writeup detailing my reasoning for this change. https://github.com/kcaf/PokeRadar/wiki/A-webpage-opened%3F!

As for your suggestion, I'll look into that. It's possible the Language file is not importing the right value.

**Comment by kcaf** [comment] 2018-02-07 04:43
I've done away with this "pop up" feature and replace it with [this](https://github.com/kcaf/PokeRadar/wiki/CPU-Donations)

**Closed** 2018-02-10 12:29 UTC
